### ISSUE TITLE
KotlinNullPointerException during triangulation

### ISSUE THREAD

**Issue by RezMike** [korlibs/korge-samples#29]
I have this error when running triangulation sample:

```
kotlin.KotlinNullPointerException
	at com.soywiz.korma.triangle.internal.Sweep.finalizationPolygon(Poly2Tri.kt:215)
	at com.soywiz.korma.triangle.internal.Sweep.triangulate(Poly2Tri.kt:196)
	at com.soywiz.korma.triangle.triangulate.TriangulateKt.triangulate(Triangulate.kt:12)
	at MainKt$main$2$1$1.invoke(main.kt:45)
        ...
```

![error](https://user-images.githubusercontent.com/19624167/85235143-dbfc3d80-b43c-11ea-9f98-d9b4765646e4.gif)

**Comment by soywiz** [comment]
That triangulation is invalid.

http://r3mi.github.io/poly2tri.js/
https://github.com/r3mi/poly2tri.js/

https://github.com/nerik/poly2trihx
http://nerik.github.io/poly2trihx/

**Comment by soywiz** [comment]
The haxe version sample detects invalid polygons and doesn't allow you to add the lines + allows to add holes. If you want to port the sample to support that too, would be great
